language: node_js

node_js:
- '0.10'

env:
  global:
    secure: V+79Mdvq8KDMCPr5gzGYGwtvyX1fc6gY5Xi6EdM2KB1IlkiZut5Trv1R42s9ppq9BEjDkTdwHPtx9Sy3j40rEx1kNI3smTNtlzIXFcqkEcC3ZZM9RfUPtTVvmR7KB4wyPnnbJucFJY/hJq4qsVjgONsesZgDqPOSGm+4T9owmME=

script:
  - echo hello world

after_success:
  - git config --global user.email "superdweebie@gmail.com"
  - git config --global user.name "Travis-CI"
  - mkdir gh-pages
  - cd gh-pages
  - git init
  - git remote add -t gh-pages -f origin https://${GITHUBTOKEN}@github.com/superdweebie/tcitest
  - git checkout gh-pages
  - cp ../index.html index.html
  - git add .
  - git commit -m "Travis build $TRAVIS_BUILD_NUMBER pushed to gh-pages"
  - git push -f origin gh-pages
