language: node_js

node_js:
- '0.10'

env:
  global:
    secure: V+79Mdvq8KDMCPr5gzGYGwtvyX1fc6gY5Xi6EdM2KB1IlkiZut5Trv1R42s9ppq9BEjDkTdwHPtx9Sy3j40rEx1kNI3smTNtlzIXFcqkEcC3ZZM9RfUPtTVvmR7KB4wyPnnbJucFJY/hJq4qsVjgONsesZgDqPOSGm+4T9owmME=

script:
  - echo hello world
